### PR TITLE
Update libdeflate v1.19

### PR DESCRIPTION
**Pull request by dajhorn**
https://github.com/ebiggers/libdeflate/releases/tag/v1.19

### CODE REVIEW

**Comment by dajhorn** [comment]
Bisecting upstream:

- ebiggers/libdeflate@778d460ef09ad0e44655055d257dbc4a256f6210 is the last commit that passes `make distcheck`.
- ebiggers/libdeflate@7380364b4e47b91a94334e8599a47b0e7aa19a1f is the first commit that fails `make distcheck`.

Which happened between the v1.15 and v1.16 tags.

**Comment by ace-dent** [comment]
Please be aware that v1.19 may reduce compression for some image files, for compatibility with broken deflate decompressors.
https://github.com/ebiggers/libdeflate/issues/323

**Comment by amadvance** [comment]
Hi @dajhorn
Consider that "make check" also compares the compressed data, so it's expected to fail if the compression algo changes or improves.
To make it pass you have to update also the check.lst file in git.

**Comment by dajhorn** [comment]
The `make distcheck` failure is indeed caused by a compression improvement.  ImageMagick reports that the output files are pixel-identical to the input files.

```
$ find -type f -iname \*.png -exec bash -c 'echo $(identify -format '%#' {}) {}' \; | sort | grep -v mappy-
1cb2542b3bebf10172e0c9498dfeaa5460a8885fecd1482c5044fa6bbc026190 ./_build/sub/basn3p01.png
1cb2542b3bebf10172e0c9498dfeaa5460a8885fecd1482c5044fa6bbc026190 ./test/basn3p01.png
295fe76227f9704c45caa157576ae49e703ad9d1ebbd8c3c7cf65027e4f77a3a ./_build/sub/basn3p02.png
295fe76227f9704c45caa157576ae49e703ad9d1ebbd8c3c7cf65027e4f77a3a ./test/basn3p02.png
2eb6a2cb3166e9c188add371157e9f81caa18fdf34d218844ed930b53b7431d2 ./_build/sub/basn6a08.png
2eb6a2cb3166e9c188add371157e9f81caa18fdf34d218844ed930b53b7431d2 ./test/basn6a08.png
3ff78c7d0ac9033c81fbcc389478d7a594ef5508979e1b6a63cfd5b7f1949beb ./_build/sub/basn2c08.png
3ff78c7d0ac9033c81fbcc389478d7a594ef5508979e1b6a63cfd5b7f1949beb ./test/basn2c08.png
72a4bb9861f45e0d15b23866455d11763cde6bb3a2a7a8101e6febdf0a1494fd ./_build/sub/italy.png
72a4bb9861f45e0d15b23866455d11763cde6bb3a2a7a8101e6febdf0a1494fd ./test/italy.png
93302575430e4e81bab5b40e7c6ba066762f14595859f08a1c5d02401605cacc ./_build/sub/basn3p04.png
93302575430e4e81bab5b40e7c6ba066762f14595859f08a1c5d02401605cacc ./test/basn3p04.png
a7abc212cf1a44c85df377773f3722dc118f0c4159df89fdac2dfe6911abe378 ./_build/sub/basn6a04.png
a7abc212cf1a44c85df377773f3722dc118f0c4159df89fdac2dfe6911abe378 ./test/basn6a04.png
bc813894fd6e034b5c2c35bd5e0b97d821338ddf9c8e5b594c74a48f888b4dc4 ./_build/sub/basn3p08.png
bc813894fd6e034b5c2c35bd5e0b97d821338ddf9c8e5b594c74a48f888b4dc4 ./test/basn3p08.png
```

**Pull request merged**
